hosts:
  - name: pi-hole
    ip: 192.168.0.6
    role: dns
    os: ubuntu
    distro_version: "22.04.5 LTS"
    purpose: Pi-hole DNS server and adblocker
    notes: runs as LXC on Proxmox

  - name: notifiarr
    ip: 192.168.0.38
    role: media-acquisition
    os: ubuntu
    distro_version: "22.04.5 LTS"
    purpose: media download tool
    notes: runs as LXC on Proxmox

  - name: prowlarr
    ip: 192.168.0.26
    role: media-acquisition
    os: ubuntu
    distro_version: "22.04.5 LTS"
    purpose: media download tool
    notes: runs as LXC on Proxmox

  - name: readarr
    ip: 192.168.0.33
    role: media-acquisition
    os: ubuntu
    distro_version: "22.04.5 LTS"
    purpose: media download tool
    notes: runs as LXC on Proxmox

  - name: sonarr
    ip: 192.168.0.50
    role: media-acquisition
    os: ubuntu
    distro_version: "22.04.5 LTS"
    purpose: media download tool
    notes: runs as LXC on Proxmox

  - name: arr-04
    ip: 192.168.0.22
    role: media-acquisition
    os: ubuntu
    distro_version: "22.04.5 LTS"
    purpose: media download tool
    notes: runs as LXC on Proxmox

  - name: radarr
    ip: 192.168.0.42
    role: media-acquisition
    os: ubuntu
    distro_version: "22.04.5 LTS"
    purpose: media download tool
    notes: runs as LXC on Proxmox

  - name: jellyfin
    ip: 192.168.0.31
    role: media-frontend
    os: ubuntu
    distro_version: "22.04.5 LTS"
    purpose: media library frontend
    notes: runs as LXC on Proxmox
    
  - name: sabnzbd
    ip: 192.168.0.11
    role: media-acquisition
    os: ubuntu
    distro_version: "22.04.5 LTS"
    purpose: media download tool
    notes: runs as LXC on Proxmox

  - name: linkwarden
    ip: 192.168.0.105
    role: bookmarks
    os: ubuntu
    distro_version: "22.04.4 LTS"
    purpose: link and bookmark management 
    notes: runs as LXC on Proxmox

  - name: gitea
    ip: 192.168.0.107
    role: git
    os: debian
    distro_version: "13.3"
    purpose: self hosted git solution
    notes: runs as LXC on Proxmox

  - name: drawio
    ip: 192.168.0.51
    role: tools
    os: debian
    distro_version: "13.5"
    purpose: xml based graphing and diagrams
    notes: runs as LXC on Proxmox

  - name: uptimekuma
    ip: 192.168.0.177
    role: monitoring
    os: debian
    distro_version: "13.3"
    purpose: monitoring
    notes: runs as LXC on Proxmox

  - name: downloader
    ip: 192.168.0.12
    role: media-acquisition
    os: debian
    distro_version: "13.5"
    purpose: media download tool
    notes: runs as LXC on Proxmox

  - name: fladder
    ip: 192.168.0.108
    role: media-frontend
    os: debian
    distro_version: "13.3"
    purpose: alternate media frontend
    notes: runs as LXC on Proxmox

  - name: vaultwarden
    ip: 192.168.0.220
    role: security
    os: debian
    distro_version: "13.3"
    purpose: password and secret manager
    notes: runs as LXC on Proxmox
  

  - name: nas-01
    ip: 192.168.0.10
    role: nas
    os: debian
    distro_version: "12.0"
    purpose: nas storage for homelab
    notes: runs as VM on Proxmox

  - name: pfsense
    ip: 192.168.0.1
    role: firewall
    os: freebsd
    distro_version: "15.0"
    purpose: main router and firewall for homelab
    notes: runs as VM on proxmox

  - name: lab-debian-vm
    ip: 192.168.0.204
    role: lab
    os: debian
    distro_version: "12"
    purpose: lab for learning
    notes: runs as VM on Proxmox

  - name: recovery-ubuntu-vm
    ip: 10.30.1.11
    role: lab
    os: ubuntu
    distro_version: "20.04.6 LTS"
    purpose: lab for learning
    notes: runs as VM on Proxmox, isolated VLAN by design (AI agent sandbox) 

  - name: k8s-cp-01
    ip: 192.168.0.58
    role: k8s-lab-control-plane
    os: ubuntu
    distro_version: "26.04 LTS"
    purpose: kubernetes lab cluster control plane node
    notes: runs as VM on Proxmox

  - name: k8s-worker-01
    ip: 192.168.0.59
    role: k8s-lab-worker
    os: ubuntu
    distro_version: "26.04 LTS"
    purpose: kubernetes lab cluster worker node 1
    notes: runs as VM on Proxmox

  - name: k8s-worker-02
    ip: 192.168.0.60
    role: k8s-lab-worker
    os: ubuntu
    distro_version: "26.04 LTS"
    purpose: kubernetes lab cluster worker node 2
    notes: runs as VM on Proxmox

  - name: ctrl-ansible-01
    ip: 192.168.0.210
    role: automation
    os: ubuntu
    distro_version: "26.04 LTS"
    purpose: external control node for k8s cluster and ansible automation
    notes: runs as VM on Proxmox
    
  - name: rocky-node-01
    ip: 192.168.0.211
    role: k8s-control-plane
    os: rocky-linux
    distro_version: "9.7"
    purpose: kubernetes control plane
    notes: runs as VM on Proxmox

  - name: rocky-node-02
    ip: 192.168.0.212
    role: k8s-worker
    os: rocky-linux
    distro_version: "9.7"
    purpose: kubernetes worker node 
    notes: runs as VM on Proxmox

  - name: rocky-node-03
    ip: 192.168.0.213
    role: k8s-worker
    os: rocky-linux
    distro_version: "9.7"
    purpose: kubernetes worker node
    notes: runs as VM on Proxmox

  - name: rocky-node-04
    ip: 192.168.0.214
    role: k8s-worker
    os: rocky-linux
    distro_version: "9.7"
    purpose: kubernetes worker node
    notes: runs as VM on Proxmox

  - name: rocky-node-05
    ip: 192.168.0.215
    role: k8s-worker
    os: rocky-linux
    distro_version: "9.7"
    purpose: kubernetes worker node
    notes: runs as VM on Proxmox

  - name: rocky-node-06
    ip: 192.168.0.216
    role: k8s-worker
    os: rocky-linux
    distro_version: "9.7"
    purpose: kubernetes worker node
    notes: runs as VM on Proxmox

  - name: drizzle-labs
    ip: 192.168.0.201
    role: ai-agent
    os: ubuntu
    distro_version: "24.04.4 LTS"
    purpose: hermes agent housing
    notes: runs as standalone mini pc

  - name: pve-01
    ip: 192.168.0.101
    role: hypervisor
    os: proxmox
    distro_version: "8.4.16"
    purpose: proxmox host
    notes: os for dell R710 server
  