[all:vars]
ansible_user=ansible

[dns]
pi-hole ansible_host=192.168.0.6

[media_acquisition]
notifiarr ansible_host=192.168.0.38
prowlarr ansible_host=192.168.0.26
readarr ansible_host=192.168.0.33
sonarr ansible_host=192.168.0.50
arr-04 ansible_host=192.168.0.22
radarr ansible_host=192.168.0.42
sabnzbd ansible_host=192.168.0.11
downloader ansible_host=192.168.0.12

[media_frontend]
jellyfin ansible_host=192.168.0.31
fladder ansible_host=192.168.0.108

[tools]
linkwarden ansible_host=192.168.0.105
gitea ansible_host=192.168.0.107
drawio ansible_host=192.168.0.51

[monitoring]
uptimekuma ansible_host=192.168.0.177

[security]
vaultwarden ansible_host=192.168.0.220

[nas]
nas-01 ansible_host=192.168.0.10

[firewall]
# pfsense ansible_host=192.168.0.1 FREEBSD compatibility issues.

[lab_machines:children]
k8s_lab
general_lab

[general_lab]
lab-debian-vm ansible_host=192.168.0.204
recovery-ubuntu-vm ansible_host=10.30.1.11

[k8s_lab]
k8s-cp-01 ansible_host=192.168.0.58
k8s-worker-01 ansible_host=192.168.0.59
k8s-worker-02 ansible_host=192.168.0.60

[automation]
ctrl-ansible-01 ansible_host=localhost ansible_connection=local

[k8s_cluster:children]
k8s_control_planes
k8s_workers

[k8s_control_planes]
rocky-node-01 ansible_host=192.168.0.211

[k8s_workers]
rocky-node-02 ansible_host=192.168.0.212
rocky-node-03 ansible_host=192.168.0.213
rocky-node-04 ansible_host=192.168.0.214
rocky-node-05 ansible_host=192.168.0.215
rocky-node-06 ansible_host=192.168.0.216

[others]
drizzle-labs ansible_host=192.168.0.201
rainlabs-main ansible_host=192.168.0.200

[hypervisor]
pve-01 ansible_host=192.168.0.101

[lxcs:children]
dns
media_acquisition
media_frontend
security
monitoring
tools

[vms:children]
nas
firewall
lab_machines
automation
k8s_cluster
